#!/bin/bash

#SBATCH --job-name=intranode
#SBATCH --nodes=2
#SBATCH --ntasks-per-node 1
#SBATCH --exclusive
#SBATCH --wait-all-nodes=1

export FI_PROVIDER=efa

export MASTER_ADDR=$(scontrol show hostname ${SLURM_NODELIST} | head -n 1)
export WORLD_SIZE=$SLURM_NNODES

mpirun -N 1 bash -c 'echo $(hostname): $(cat /sys/devices/virtual/dmi/id/board_asset_tag | tr -d " ")'

srun --mpi=pmix --cpu-bind=none --container-image ./vllm-ep.sqsh bash -c 'PYTHONPATH=$(echo /DeepEP/install/lib/python*/site-packages):$PYTHONPATH RANK=$SLURM_PROCID python3 /DeepEP/tests/test_low_latency.py'
